"""Regression tests: ai_corrector.py consolidation (2026-09-21).

The five byte-identical copies of the module (proven by pairwise ``cmp`` on
2026-09-21, md5 2f53a5ea6dd82944e6fe42eddc9a217f, 393 lines each) were
consolidated into the canonical implementation at
``packages/nlp/ai_corrector.py``:

    packages/nlp/ai_corrector.py                                  (canonical)
    hf-space/packages/nlp/ai_corrector.py                         (sync snapshot —
                                                                   regenerated by
                                                                   scripts/sync-hf-space.sh)
    packages/file_processor/modules/nlp/ai_corrector.py           (re-export shim)
    packages/handwriting/modules/nlp/ai_corrector.py              (re-export shim)
    packages/omnifile/modules/nlp/ai_corrector.py                 (re-export shim)

These tests lock the consolidation in place: every historical import path must
still resolve to the canonical ``AICorrector`` class object, and the vendored
paths must remain thin shims (no copy-paste regression).
"""

from __future__ import annotations

import importlib
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]  # tests/ is directly under repo root
CANONICAL = REPO_ROOT / "packages" / "nlp" / "ai_corrector.py"
SHIM_PATHS = [
    REPO_ROOT / "packages" / "file_processor" / "modules" / "nlp" / "ai_corrector.py",
    REPO_ROOT / "packages" / "handwriting" / "modules" / "nlp" / "ai_corrector.py",
    REPO_ROOT / "packages" / "omnifile" / "modules" / "nlp" / "ai_corrector.py",
]


def _purge_modules() -> None:
    for key in list(sys.modules):
        if key == "modules" or key.startswith("modules."):
            del sys.modules[key]


def test_canonical_module_exists_and_exposes_ai_corrector() -> None:
    assert CANONICAL.is_file(), "canonical packages/nlp/ai_corrector.py missing"
    sys.path.insert(0, str(REPO_ROOT))
    try:
        mod = importlib.import_module("packages.nlp.ai_corrector")
        assert hasattr(mod, "AICorrector")
    finally:
        sys.path.pop(0)
        _purge_modules()


def test_shims_are_thin_reexports() -> None:
    for shim in SHIM_PATHS:
        assert shim.is_file(), f"missing shim: {shim}"
        text = shim.read_text(encoding="utf-8")
        assert "Consolidation shim" in text, f"{shim} is no longer a marked shim"
        assert "from packages.nlp.ai_corrector import AICorrector" in text
        # A thin shim must stay small; the real implementation is ~13KB
        assert shim.stat().st_size < 3000, (
            f"{shim} grew to {shim.stat().st_size} bytes — looks like a "
            "full copy re-appeared; import packages.nlp.ai_corrector instead"
        )


@pytest.mark.parametrize("pkg_root", [str(p) for p in [
    REPO_ROOT / "packages" / "file_processor",
    REPO_ROOT / "packages" / "handwriting",
    REPO_ROOT / "packages" / "omnifile",
]])
def test_old_import_paths_resolve_to_canonical_class(pkg_root: str) -> None:
    from packages.nlp.ai_corrector import AICorrector as canonical  # noqa: PLC0415

    sys.path.insert(0, str(REPO_ROOT))
    sys.path.insert(0, pkg_root)
    try:
        mod = importlib.import_module("modules.nlp.ai_corrector")
        assert mod.AICorrector is canonical, (
            f"{pkg_root}: old import path no longer resolves to the canonical class"
        )
    finally:
        sys.path.pop(0)
        sys.path.pop(0)
        _purge_modules()


def test_hf_space_snapshot_matches_canonical() -> None:
    """hf-space/packages/nlp is regenerated by scripts/sync-hf-space.sh; the
    tracked snapshot must not drift from the canonical source."""
    snap = REPO_ROOT / "hf-space" / "packages" / "nlp" / "ai_corrector.py"
    assert snap.is_file(), "hf-space snapshot missing"
    assert snap.read_bytes() == CANONICAL.read_bytes(), (
        "hf-space/packages/nlp/ai_corrector.py drifted from the canonical module — "
        "run ./scripts/sync-hf-space.sh"
    )


def test_hf_space_sync_verify_mode_reports_no_drift_for_nlp() -> None:
    """Run the repo's own verification script; it must exit 0 (no drift).

    Skipped when bash is unavailable (non-POSIX sandbox).
    """
    script = REPO_ROOT / "scripts" / "sync-hf-space.sh"
    if not script.is_file():
        pytest.skip("scripts/sync-hf-space.sh not present")
    try:
        proc = subprocess.run(
            ["bash", str(script), "--verify"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        pytest.skip(f"sync-hf-space.sh could not run here: {exc}")
    assert proc.returncode == 0, (
        f"sync-hf-space.sh --verify reported drift (exit {proc.returncode}):\n"
        f"{proc.stdout[-2000:]}\n{proc.stderr[-2000:]}"
    )
