apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: omnimedical
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-upload-config
  namespace: omnimedical
data:
  client_max_body_size: "50m"
