apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnimedical.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omnimedical.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "" | quote }}
