port 26379
sentinel monitor omnimedical-redis redis 6379 2
sentinel down-after-milliseconds omnimedical-redis 30000
sentinel failover-timeout omnimedical-redis 180000
sentinel parallel-syncs omnimedical-redis 1
protected-mode yes
bind 0.0.0.0
loglevel notice
