# src/ner/fine_tune_jais_ner.py
"""
Fine-tune Jais for Medical NER using PEFT (LoRA) to reduce memory.

Uses prompt-completion format: given medical text → output structured entities.
Dataset is generated by scripts/create_jais_prompt_dataset.py.

Requirements:
    pip install transformers peft accelerate bitsandbytes datasets

GPU: 24GB+ recommended (8-bit quantization + LoRA reduces to ~12GB).

Usage:
    tuner = JaisNERFineTuner()
    dataset = tuner.prepare_dataset()
    tuner.train(dataset, epochs=3)

    # Load fine-tuned model for inference
    from peft import PeftModel, PeftConfig
    config = PeftConfig.from_pretrained("outputs/jais_ner_finetuned")
    base = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, device_map="auto")
    model = PeftModel.from_pretrained(base, "outputs/jais_ner_finetuned")
"""
import logging

import torch
from datasets import Dataset, load_dataset
from peft import LoraConfig, TaskType, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments

logger = logging.getLogger(__name__)


class JaisNERFineTuner:
    """Fine-tune Jais-13B for medical NER using LoRA."""

    def __init__(self, model_name: str = "core42/jais-13b-chat"):
        logger.info(f"Initializing Jais NER FineTuner with {model_name}")
        self.model_name = model_name
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

        # Load base model with 8-bit quantization
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map="auto",
            torch_dtype=torch.bfloat16,
            load_in_8bit=True,
            trust_remote_code=True,
        )

        # Configure LoRA for parameter-efficient fine-tuning
        lora_config = LoraConfig(
            r=16,                  # Rank
            lora_alpha=32,         # Alpha scaling
            target_modules=["q_proj", "v_proj"],  # Target attention layers
            lora_dropout=0.05,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
        )
        self.model = get_peft_model(self.model, lora_config)
        self.model.print_trainable_parameters()

    def prepare_dataset(
        self,
        hf_dataset_name: str = "DrAbdulmalek/arabic-medical-ocr-corrections",
    ) -> Dataset:
        """
        Prepare prompt-completion pairs from HF dataset for NER fine-tuning.

        Uses correct_text (preferred) or incorrect_ocr_output as source.
        Completions are placeholder — replace with actual annotations for best results.
        """
        logger.info(f"Loading dataset: {hf_dataset_name}")
        df = load_dataset(hf_dataset_name, split="train").to_pandas()

        def create_prompt(example: dict) -> dict:
            text = example.get("correct_text", "") or example.get("incorrect_ocr_output", "")
            prompt = (
                f"أنت مساعد طبي متخصص في استخراج الكيانات الطبية.\n\n"
                f"نص: {text}\n\n"
                f"استخرج الكيانات:\n"
                f"- دواء:\n- مرض:\n- عرض:\n- جرعة:\n- تاريخ:\n\n"
                f"الإجابة:"
            )
            completion = "دواء: -\nمرض: -\nجرعة: -\nعرض: -\nتاريخ: -"
            return {"prompt": prompt, "completion": completion}

        dataset = Dataset.from_pandas(df)
        dataset = dataset.map(create_prompt)
        logger.info(f"Prepared {len(dataset)} prompt-completion pairs")
        return dataset

    def train(
        self,
        dataset: Dataset,
        output_dir: str = "outputs/jais_ner_finetuned",
        epochs: int = 3,
        batch_size: int = 2,
        grad_accum: int = 8,
    ) -> Trainer:
        """
        Fine-tune Jais on NER dataset.

        Args:
            dataset: Prompt-completion dataset.
            output_dir: Model save directory.
            epochs: Number of training epochs.
            batch_size: Per-device batch size (keep small with LoRA+8bit).
            grad_accum: Gradient accumulation steps (effective batch = batch_size * grad_accum).
        """
        training_args = TrainingArguments(
            output_dir=output_dir,
            num_train_epochs=epochs,
            per_device_train_batch_size=batch_size,
            gradient_accumulation_steps=grad_accum,
            learning_rate=2e-4,
            fp16=True,
            save_strategy="epoch",
            logging_steps=10,
            optim="adamw_8bit",
            warmup_ratio=0.05,
            report_to="none",
            max_grad_norm=1.0,
        )

        trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=dataset,
            tokenizer=self.tokenizer,
        )

        logger.info("Starting Jais NER fine-tuning...")
        trainer.train()
        trainer.save_model(output_dir)
        logger.info(f"Fine-tuned model saved to {output_dir}")
        return trainer


if __name__ == "__main__":
    import argparse
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--output_dir", default="outputs/jais_ner_finetuned")
    args = parser.parse_args()

    tuner = JaisNERFineTuner()
    dataset = tuner.prepare_dataset()
    tuner.train(dataset, epochs=args.epochs, output_dir=args.output_dir)
