#!/usr/bin/env python3
"""
Merge a PR on GitHub via the REST API (squash merge).

Usage:
    GH_TOKEN=... python scripts/merge_pr.py <PR_NUMBER>
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
import urllib.error

REPO = "DrAbdulmalek/omni-medical-suite"
TOKEN = os.environ.get("GH_TOKEN", "")
if not TOKEN:
    print("❌ GH_TOKEN env var not set", file=sys.stderr)
    sys.exit(1)


def merge_pr(pr_number: int) -> int:
    payload = {
        "commit_title": f"feat: v1.1.0-rc1 — P0+P1+P2 hardening sprint (#{pr_number})",
        "commit_message": """Squash merge of PR #66 — feat/rc-hardening-p0 → main

Consolidates 15 commits across P0 (7 items), P1 (4 items), P2 (4 items).

Highlights:
- Lazy OCR factories (PEP 562 __getattr__ backward-compat)
- Structured decision log (JSON line per decision)
- HF dataset staging queue (O(1) save + batched flush)
- Field extractor: multi-line + bilingual + confidence + safe signature
- Benchmark reporter: CSV/JSON export + aggregate_metrics
- AppImage build pipeline (Manjaro + Linux x86_64)
- CI matrix: Python 3.10/3.11/3.12 + Manjaro/Arch + HF smoke + Colab + LFS audit
- Git LFS coverage: 50+ patterns, 32/32 files covered
- 163 tests pass (P0: 95 + P1: 66 + scanner integration)
- 11 AppImage smoke tests (conditional)

No breaking changes — full backward compatibility.

🤖 Generated by Z.ai (P2 hardening sprint)""",
        "merge_method": "squash",
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/pulls/{pr_number}/merge",
        data=data,
        method="PUT",
        headers={
            "Authorization": f"token {TOKEN}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            print(f"✅ PR #{pr_number} merged: {result.get('message', 'OK')}")
            print(f"   SHA: {result.get('sha', 'unknown')}")
            print(f"   Merged: {result.get('merged', False)}")
            return 0
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8")
        print(f"❌ HTTP {e.code}: {e.reason}", file=sys.stderr)
        print(body, file=sys.stderr)
        return 1
    except Exception as e:
        print(f"❌ {type(e).__name__}: {e}", file=sys.stderr)
        return 1


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python merge_pr.py <PR_NUMBER>", file=sys.stderr)
        return 1
    pr_number = int(sys.argv[1])
    return merge_pr(pr_number)


if __name__ == "__main__":
    sys.exit(main())
