#!/usr/bin/env python3
"""
OmniMedical Suite — Dependency Update Script.

Checks for outdated packages and known security vulnerabilities.
Outputs a report and exits with code 1 if issues are found.

Usage:
    python scripts/update_dependencies.py
    python scripts/update_dependencies.py --fix   # Auto-update safe packages
"""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def get_outdated() -> list[dict]:
    """Get list of outdated pip packages."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "list", "--outdated", "--format=json"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        pass
    return []


def check_safety() -> list[dict]:
    """Check for known security vulnerabilities using pip-audit."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip_audit", "--format", "json"],
            capture_output=True, text=True, timeout=120,
        )
        if result.stdout.strip():
            return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError):
        # pip-audit not installed — try safety as fallback
        try:
            result = subprocess.run(
                ["safety", "check", "--json", "--output", "/dev/stdout"],
                capture_output=True, text=True, timeout=120,
            )
            if result.stdout.strip():
                return json.loads(result.stdout)
        except Exception:
            pass
    return []


def create_report(outdated: list[dict], vulnerabilities: list[dict]) -> str:
    """Generate a markdown report."""
    lines = [
        f"# Dependency Update Report — {datetime.now().strftime('%Y-%m-%d')}",
        "",
    ]

    if outdated:
        lines.append(f"## Outdated Packages ({len(outdated)})")
        lines.append("| Package | Current | Latest | Type |")
        lines.append("|---------|---------|--------|------|")
        for pkg in outdated:
            lines.append(
                f"| {pkg.get('name', '?')} | {pkg.get('version', '?')} "
                f"| {pkg.get('latest_version', '?')} | {pkg.get('latest_version_type', '?')} |"
            )
        lines.append("")

    if vulnerabilities:
        lines.append(f"## Security Vulnerabilities ({len(vulnerabilities)})")
        lines.append("| Package | Vulnerability | Severity | Fix |")
        lines.append("|---------|--------------|----------|-----|")
        for vuln in vulnerabilities:
            name = vuln.get("name", vuln.get("package", "?"))
            vid = vuln.get("vulnerability_id", vuln.get("id", "?"))
            fix = vuln.get("fix_versions", ["N/A"])
            fix_str = ", ".join(fix) if isinstance(fix, list) else str(fix)
            lines.append(f"| {name} | {vid} | {vuln.get('severity', '?')} | {fix_str} |")
        lines.append("")

    if not outdated and not vulnerabilities:
        lines.append("All packages are up-to-date with no known vulnerabilities.")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by `scripts/update_dependencies.py`*")
    return "\n".join(lines)


def main():

    print("Checking outdated packages...")
    outdated = get_outdated()
    print(f"  Found {len(outdated)} outdated packages")

    print("Checking security vulnerabilities...")
    vulnerabilities = check_safety()
    print(f"  Found {len(vulnerabilities)} vulnerabilities")

    report = create_report(outdated, vulnerabilities)
    print("\n" + report)

    # Save report
    report_path = Path("dependency_update_report.md")
    report_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved to: {report_path}")

    if outdated or vulnerabilities:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
